### ISSUE TITLE
Oracular script asking for a newer hyprwayland-scanner version

### ISSUE THREAD

**Issue by mornec-ridhut** [katabame/Ubuntu-Hyprland#2]
Hello,

Just submitting a bug report with regards to both the stable and nightly oracular script. The hyprland devs [just released a new version of hyprwayland-scanner](https://github.com/hyprwm/hyprwayland-scanner/releases/tag/v0.4.2) and it broke compatibility with this build script. Now running either the stable or nightly script returns this error:

```
CMake Error at /usr/share/cmake-3.30/Modules/FindPkgConfig.cmake:645 (message):
    The following required packages were not found:

        - hyprwayland-scanner>=0.4.2

Call Stack (most recent call first):
    /usr/share/cmake-3.30/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
    CMakeLists.txt:54 (pkg_check_modules)
```

Is there any workaround to this issue or should I just wait for a script update.

Regards,

**Comment by romosborne** [comment]
I think it's just an issue with the compilation order.  A simple workaround is to build the `hyprwayland-scanner` before the `xdg-desktop-portal-hyprland`.

IE.  Move [block 97](https://github.com/katabame/Ubuntu-Hyprland/blob/main/oracular.sh#L190-L199) before [block 96](https://github.com/katabame/Ubuntu-Hyprland/blob/main/oracular.sh#L179-L188)

**Comment by katabame** [comment]
Hello @mornec-ridhut, thanks for letting know that script is broken.

As @romosborne said, this issue happened by the compilation order.
I moved `block 97 (hyprwayland-scanner)` before `block 96 (xdg-desktop-portal-hyprland)` and seems the script back to working normally. (Thanks for workaround!)

Oracular script has been updated (1548f0fb6cd), so please try run the script again.

Happy hyprlanding!
